household_data <- read.table("household_power_consumption.txt", sep=";",header=TRUE,  colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "character"))
household_data$Date <- as.Date(household_data$Date,format="%d/%m/%Y")
household_data$Global_active_power <- as.numeric(household_data$Global_active_power)
household_data$Global_reactive_power <- as.numeric(household_data$Global_reactive_power)
household_data$Voltage <- as.numeric(household_data$Voltage)
household_data$Global_intensity <- as.numeric(household_data$Global_intensity)
household_data$Sub_metering_1 <- as.numeric(household_data$Sub_metering_1)
household_data$Sub_metering_2 <- as.numeric(household_data$Sub_metering_2)
household_data$Sub_metering_3 <- as.numeric(household_data$Sub_metering_3)
household_data.sub <- subset(household_data, household_data$Date >= "2007-02-01" & household_data$Date <= "2007-02-02")
household_data.sub$DateTime <- paste(household_data.sub$Date, household_data.sub$Time)
household_data.sub$DateTime <- strptime(household_data.sub$DateTime, format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(1,1))
png(filename="plot3.png")
par(mfrow=c(1,1))
plot(household_data.sub$DateTime, household_data.sub$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(household_data.sub$DateTime, household_data.sub$Sub_metering_2, type = "l", col = "red")
lines(household_data.sub$DateTime, household_data.sub$Sub_metering_3, type = "l", col = "blue")
legend("topright", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=1.0)
dev.off()

