household_data <- read.table("household_power_consumption.txt", sep=";",header=TRUE,  colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "character"))
household_data$Date <- as.Date(household_data$Date,format="%d/%m/%Y")
household_data$Global_active_power <- as.numeric(household_data$Global_active_power)
household_data$Global_reactive_power <- as.numeric(household_data$Global_reactive_power)
household_data$Voltage <- as.numeric(household_data$Voltage)
household_data$Global_intensity <- as.numeric(household_data$Global_intensity)
household_data$Sub_metering_1 <- as.numeric(household_data$Sub_metering_1)
household_data$Sub_metering_2 <- as.numeric(household_data$Sub_metering_2)
household_data$Sub_metering_3 <- as.numeric(household_data$Sub_metering_3)
household_data.sub <- subset(household_data, household_data$Date >= "2007-02-01" & household_data$Date <= "2007-02-02")
household_data.sub$DateTime <- paste(household_data.sub$Date, household_data.sub$Time)
household_data.sub$DateTime <- strptime(household_data.sub$DateTime, format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(1,1))
png(filename="plot2.png")
plot(household_data.sub$DateTime, household_data.sub$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()
