household_data <- read.table("household_power_consumption.txt", sep=";",header=TRUE,  colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "character"))
household_data$Date <- as.Date(household_data$Date,format="%d/%m/%Y")
household_data$Global_active_power <- as.numeric(household_data$Global_active_power)
household_data$Global_reactive_power <- as.numeric(household_data$Global_reactive_power)
household_data$Voltage <- as.numeric(household_data$Voltage)
household_data$Global_intensity <- as.numeric(household_data$Global_intensity)
household_data$Sub_metering_1 <- as.numeric(household_data$Sub_metering_1)
household_data$Sub_metering_2 <- as.numeric(household_data$Sub_metering_2)
household_data$Sub_metering_3 <- as.numeric(household_data$Sub_metering_3)
household_data.sub <- subset(household_data, household_data$Date >= "2007-02-01" & household_data$Date <= "2007-02-02")
png(filename="plot1.png")
par(mfrow=c(1,1))
hist(household_data.sub$Global_active_power, main="Global Active Power", col = "red", breaks = 11, xlab = "Global Active Power (kilowatts)")
dev.off()
